import smtplib
import requests
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta

# --- CONFIGURATION ---
NEWS_API_KEY = os.environ.get("NEWS_API_KEY")
SENDER_EMAIL = os.environ.get("EMAIL_ADDRESS")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")
RECEIVER_EMAIL = os.environ.get("EMAIL_ADDRESS") # Sends to yourself

# We filter for high-quality tech news sources to ensure importance
SOURCES = "wired,the-verge,techcrunch,ars-technica,engadget,next-web"
KEYWORDS = '"Artificial Intelligence" OR "OpenAI" OR "ChatGPT" OR "Gemini AI" OR "NVIDIA AI"'

def get_news():
    # Get news from the last 7 days
    seven_days_ago = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    
    url = (f'https://newsapi.org/v2/everything?'
           f'q={KEYWORDS}&'
           f'sources={SOURCES}&'
           f'from={seven_days_ago}&'
           f'sortBy=popularity&'
           f'language=en&'
           f'apiKey={NEWS_API_KEY}')
    
    response = requests.get(url)
    data = response.json()
    return data.get('articles', [])[:7] # Get top 7 stories

def create_html_email(articles):
    # Basic HTML template for a "Newspaper" look
    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; color: #333;">
        <div style="background-color: #2c3e50; padding: 20px; text-align: center; color: white;">
            <h1>The Saturday AI Dispatch</h1>
            <p>Weekly Update: {datetime.now().strftime('%B %d, %Y')}</p>
        </div>
        <div style="padding: 20px;">
    """
    
    for article in articles:
        title = article.get('title', 'No Title')
        desc = article.get('description', 'No description available.')
        url = article.get('url', '#')
        source = article.get('source', {}).get('name', 'News')
        
        # Add article card to HTML
        html_content += f"""
        <div style="margin-bottom: 25px; border-bottom: 1px solid #eee; padding-bottom: 15px;">
            <h3 style="margin-top: 0; color: #2980b9;">{title}</h3>
            <p style="font-size: 12px; color: #777; font-weight: bold;">Source: {source}</p>
            <p style="line-height: 1.5;">{desc}</p>
            <a href="{url}" style="background-color: #3498db; color: white; padding: 8px 12px; text-decoration: none; border-radius: 4px; font-size: 14px;">Read Full Article</a>
        </div>
        """
        
    html_content += """
            <p style="text-align: center; color: #999; font-size: 12px; margin-top: 30px;">
                Generated by your Personal AI GitHub Bot
            </p>
        </div>
    </body>
    </html>
    """
    return html_content

def send_email():
    articles = get_news()
    
    if not articles:
        print("No news found this week.")
        return

    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"🤖 AI News: {datetime.now().strftime('%B %d')}"
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL

    # Create the HTML version
    html_body = create_html_email(articles)
    msg.attach(MIMEText(html_body, 'html'))

    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER_EMAIL, EMAIL_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())
        server.quit()
        print("News sent successfully!")
    except Exception as e:
        print(f"Error sending email: {e}")

if __name__ == "__main__":
    send_email()
